---
title: "d2"
output: html_document
date: "2026-02-18"
---

##1

```{r}
A=matrix(c(2,-1,0,1,3,3,1,2,-1,0,0,2,1,-4,-2,1,0,1,2,-1),nrow=5,ncol=4)

y=c(-8,3,-5,-17,1)

svdr=svd(A)
U=svdr$u
D=svdr$d
V=svdr$v

tol=1e-10
rang=sum(D>tol)
```

##a

```{r}
bi=U[,1:rang]
di=rang

bk=V[,(rang+1):ncol(A),drop=FALSE]
dk=ncol(A)-rang

cat("Dimenzija slike:", di, "\n")
cat("Baza slike:\n")
print(bi)

cat("\nDimenzija jezgra:", dk, "\n")
cat("Baza jezgra:\n")
print(bk)
```

```{r}
koef=t(bi)%*%y
yp=bi%*%koef
pripada=all(abs(yp-y)<1e-10)

cat("Koeficijenti u bazi slike:\n")
print(koef)
cat("Da li y pripada slici?", pripada, "\n")
```


##b


```{r}
D_inv=diag(1/D[1:rang],rang,rang)
Ap=V[,1:rang]%*%D_inv%*%t(U[,1:rang])

x1=Ap%*%y

jedinstveno=(dk == 0)
x2=x1+bk[,1]

cat("x1:\n")
print(x1)
cat("Da li je rešenje jedinstveno?", jedinstveno, "\n")

if(!jedinstveno) {
  cat("x2:\n")
  print(x2)
}
```


##2

```{r}
A=matrix(c(0,-1,2,0,2,1,-3,1,-1,2,-3,4,1,2,1,-1,-3,5,0,7),nrow=5,ncol=4)
x=c(-9,-1,-1,4,1)

print(A)
```


```{r}
s=svd(A)

k=sum(s$d>1e-10)
Q=s$u[,1:k]

cat("Ortonormirana baza:\n")
print(Q)
```


```{r}
proj=Q%*%(t(Q)%*%x)
projr= round(proj, 2)

cat("Ortogonalna projekcija vektora x na U:\n")
print(projr)
```


```{r}
vd=x-proj

en=sqrt(sum(vd^2))

cat("Vektor razlike:\n")
print(round(vd, 2))

cat("\nUdaljenost:\n")
print(en)

```
##3

```{r}
A=matrix(c(4,2,3,-3,-1,-3,-2,-2,-1),nrow=3,ncol=3)

v1=c(1,0,1)
v2=c(1,1,0)
v3=c(1,1,1)

print(A)
```


```{r}
eigen=function(A,v) {
  res=A%*%v
  lambda=res[v!=0][1]/v[v!=0][1]
  
  if (all(res==lambda*v)) {
    return(lambda)
  } else {
    return(NULL)
  }
}

lambda1=eigen(A,v1)
lambda2=eigen(A,v2)
lambda3=eigen(A,v3)

cat("Sopstvene vrednosti:\n", 
    "lambda1 =", lambda1, "\n",
    "lambda2 =", lambda2, "\n",
    "lambda3 =", lambda3)
```


```{r}
P=cbind(v1, v2, v3)
D=diag(c(lambda1, lambda2, lambda3))

Pinv=solve(P)

Ar=P%*%D%*%Pinv

print("P:")
print(P)
print("D:")
print(D)
print("Rekonstruisana A:")
print(Ar)
```

