---
title: "d34"
output: html_document
date: "2026-02-22"
---

##7.1
```{r}
A=matrix(c(1,0.5,0.5,1),nrow=2,byrow=TRUE)
b=c(2,4)
gamma=0.4       
nit=100  

x=c(0,0)      
his=matrix(NA,nrow =nit+1,ncol=3)
colnames(his)=c("iter","x1","x2")
his[1,]=c(0,x)

for (i in 1:nit) {
  grad=A%*%x-b
  x=x-gamma*grad
  his[i+1,]=c(i, x)
}

tail(his,5)

as=solve(A,b)
print(paste("Analitičko rešenje:", paste(as,collapse=", ")))
```

```{r}
hdf=as.data.frame(his)
```




```{r}
plot(hdf$x1,hdf$x2, 
     type="n", 
     xlab="x1",ylab ="x2", 
     main="Putanja gradijentnog spusta",
     sub=paste("Konačna tačka:",round(x[1],4),",",round(x[2],4)))
grid()

rbPal=colorRampPalette(c("deeppink", "cyan"))
hdf$col=rbPal(10)[as.numeric(cut(hdf$iter,breaks=10))]

lines(hdf$x1,hdf$x2,col="palevioletred")
points(hdf$x1,hdf$x2,col=hdf$col,pch=19)
n = nrow(hdf)
arrows(hdf$x1[-n],hdf$x2[-n], 
       hdf$x1[-1],hdf$x2[-1], 
       length=0.1,col="palevioletred")
```

